test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


google:
  service: GCS
  credentials:
    type: "service_account"
    project_id: ""
    private_key_id: <%= ENV['GOOGLE_ACCESS_KEY'] %>
    private_key: <%= ENV['GOOGLE_SECRET_KEY'] %>
    client_email: <%= ENV['KOHRVID_ADMIN_EMAIL'] %>
    client_id: ""
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: ""
  project: ""
  bucket: <%= ENV['GOOGLE_BUCKET'] %>

